export const songs = [
  { title: "Blinding Lights", artist: "The Weeknd" },
  { title: "Shape of You", artist: "Ed Sheeran" },
  { title: "Bohemian Rhapsody", artist: "Queen" },
  { title: "Rolling in the Deep", artist: "Adele" },
  { title: "Hotel California", artist: "Eagles" },
  { title: "Stairway to Heaven", artist: "Led Zeppelin" },
  { title: "Someone Like You", artist: "Adele" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana" },
  { title: "Imagine", artist: "John Lennon" },
  { title: "Wonderwall", artist: "Oasis" },
  { title: "Billie Jean", artist: "Michael Jackson" },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars" },
  { title: "Let It Be", artist: "The Beatles" },
  { title: "Shake It Off", artist: "Taylor Swift" },
  { title: "Hallelujah", artist: "Leonard Cohen" },
  { title: "Lose Yourself", artist: "Eminem" },
  { title: "Rolling Stone", artist: "Bob Dylan" },
  { title: "What's Going On", artist: "Marvin Gaye" },
  { title: "I Will Always Love You", artist: "Whitney Houston" },
  { title: "Born to Run", artist: "Bruce Springsteen" },
  { title: "Purple Rain", artist: "Prince" },
  { title: "No Woman, No Cry", artist: "Bob Marley" },
  { title: "Like a Rolling Stone", artist: "Bob Dylan" },
  { title: "Yesterday", artist: "The Beatles" },
  { title: "Creep", artist: "Radiohead" },
  { title: "All of Me", artist: "John Legend" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi" },
];
